### ISSUE TITLE
Support zero-copy conversion to/from images and 2D arrays

### ISSUE THREAD

**Issue by dlight** [dhardy/terr#1]
Currently the only way to create a heightmap is creating an empty one [with `Heightmap::new`](https://docs.rs/terr/0.1.2/terr/heightmap/struct.Heightmap.html#method.new), and the only way to export a heightmap is into a ncollide heightfield (or worse, a mesh) which requires converting the elements to f64 (despite `Heightmap` being generic). So this imposes a runtime cost when using this crate alongside other generative algorithms in the same map.

What about having appropriate `From` impls to types from `ndarray` and/or `image`? This can be behind a feature flag, to introduce an optional dependency.

**Comment by dhardy** [comment]
This library has a *long* way to go to become a high-quality procedural terrain generator, and to be honest I doubt I'll ever have the time to get it there, but if enough people are interested in collaborating I guess we can find a way of doing that.

I have started implementing collision detection on `Heightmap` directly, but currently it's buggy. Any attempt to provide copy-less conversion to `ncollide` objects will have to reconcile the fact that this lib uses z-up with the corner of the map on the origin (because I find this more intuitive), whereas `ncollide` uses y-up with objects centred over the origin (apparently because of the code-sharing between `nphysics2d` and `nphysics3d`.

If you'd like to start hacking on the code to implement your ideas, go ahead. There may be some conflicts with my working tree, but nothing that can't be resolved.

**Comment by dhardy** [comment]
What exactly is your goal here? Primarily this is a lib for experimentation with generation; I imagine that during optimisation most applications would end up implementing whichever algorithms they use directly on their internal data structures. I see no point in complicating this lib with highly-generic data structures.

You claim meshes are sub-optimal, but converting to a mesh allows other optimisations [see here](http://www.shamusyoung.com/twentysidedtale/?p=142) which may in fact make these the more optimal in-memory representation — and ultimately renderers all work from mesh representations anyway. For collision detection the hight-map representation *may* be more efficient however.

I will close this issue because (a) this is just a personal project and your request doesn't currently line up with my goals and (b) I'm not convinced your suggestion is actually anything other than premature optimisation anyway.
